### ISSUE TITLE
Injections SQL

### ISSUE THREAD

**Issue by vguede** [ndesmarets/qrdyn#2]
Bonjour,

Il semble que les requêtes SQL soient sujettes aux injections SQL. En effet, `addslashes` ne doit pas être utilisé pour prévenir les injections SQL (https://www.php.net/manual/function.addslashes.php). Il est recommandé d'utiliser à la place les requêtes préparées PDO non émulées (https://www.php.net/manual/class.pdo.php) ou a minima `mysqli_real_escape_string` (https://www.php.net/manual/mysqli.real-escape-string.php).

Bien cordialement,

Vincent Guédé

**Comment by ndevfr** [comment]
Bonjour,
Avez-vous réussi à faire une injection SQL dans vos tests ? Je n’ai pas l’impression que ce soit possible…
Je ne crois pas pouvoir utiliser mysqli_real_escape_string() étant donné que la variable $link est créée dans une fonction après le formatage de la requête sql (voir functions.php). S’il y a un risque avéré, il faudra que je revoie cela en profondeur (en sortant le mysqli_connect des fonctions…)

**Comment by vguede** [comment]
Je n'ai pas poussé mes tests jusque là. L'utilisation d'`addslashes` prévient les injections les plus simples (du type `' OR 1 = 1; DELETE FROM users; --`). En revanche, elle ne permet pas d'éviter les attaques plus subtiles, par exemple reposant sur les caractères multibytes (https://shiflett.org/blog/2006/addslashes-versus-mysql-real-escape-string).

Vous pourriez imaginer en effet sortir les mysqli_connect des différentes fonctions, ce qui permettrait d'ailleurs de n'ouvrir qu'une connexion par page (au lieu d'une connexion par requête SQL), ce qui soulagerait le serveur MySQL. Il suffirait pour cela d'utiliser une classe qui à l'instanciation ouvrirait la connexion dont elle garderait le handle en propriété.

**Comment by vguede** [comment]
Autre ressource sur les injections et `addslashes `: https://support.detectify.com/support/solutions/articles/48001048942-sql-injection

**Comment by ndevfr** [comment]
J’aime bien l’idée d’ « une classe qui à l'instanciation ouvrirait la connexion dont elle garderait le handle en propriété » mais je dois avouer que je ne vois pas comment faire cela techniquement…

**Comment by vguede** [comment]
Par exemple, une classe `DB`, instanciée dans `index.php`. Dans son constructeur, le `mysqli_connect`, qui stocke dans une propriété privée `$_link` le lien de connexion. Ensuite, remplacer toutes les fonctions `sql_*` de `functions.php` par des méthodes de cette classe. Enfin, ajouter une méthode publique `escape `qui appellera `mysqli_real_escape_string` en utilisant la propriété `$_link`.

Si vous connaissez la POO, cela se fera sans difficulté, si ce n'est refactoriser le code pour appeler les méthodes de la classe au lieu des fonctions, et utiliser `DB::escape` au lieu de `addslashes`. Sinon, ça sera un peu plus long ;o)

**Comment by vguede** [comment]
Dans votre contexte, l'utilisation d'une classe avec des méthodes et des propriétés statiques serait probablement pertinente.

**Comment by ndevfr** [comment]
A défaut de tout reprogrammer en utilisant une classe (je n'ai pas le temps pour le moment), je viens de mettre à jour les différentes fonctions sql_ utilisées : 
- sql_select(table, where, order) ;
- sql_select_unique(table, where) ;
- sql_insert(table, donnees) ;
- sql_update(table, donnees, where) ;
- sql_delete(table, where)

Tous les paramètres injectés dans la requête sql passent ainsi par la fonction real_escape_string.
Ce n'est peut-être pas la manière la plus élégante mais il n'y a plus d'injection SQL possible.

**Comment by vguede** [comment]
> A défaut de tout reprogrammer en utilisant une classe (je n'ai pas le temps pour le moment), je viens de mettre à jour les différentes fonctions sql_ utilisées :

C'est un très bon argument ;o)

Bravo pour votre réactivité ! Pour votre prochaine application, cela ira beaucoup plus vite car dès le début vous serez sensibilisé aux différentes failles de sécurité connues (la bible est là : https://owasp.org/) et aux méthodes pour les prévenir. 

Bonne fin de week end.

**Comment by vguede** [comment]
Un dernier conseil si je puis me permettre. Pour une prochaine application, je vous conseillerais :
* Soit d'utiliser PDO, avec des requêtes préparées non émulées => vous serez sûr à 100 % de ne pas avoir d'injection SQL et de ne pas oublier les protections
* Si vous avez le temps, de passer à un framework type Symfony qui avec son ORM Doctrine vous protègera des injections SQL (entre autres), avec son moteur de template Twig vous protègera des failles XSS et dont les formulaires sont protégés par défaut des failles CSRF. Mais il faut être bien à l'aise avec la POO, et la courbe d'apprentissage est ardue.
